### ISSUE TITLE
Setting value inside of if-statement messes up the coloring

### ISSUE THREAD

**Issue by ErikReider** [matbme/tree-sitter-vala#4]
![image](https://user-images.githubusercontent.com/35975961/154752691-d71fcf97-cbf0-4958-9b51-778133373b0e.png)

**Comment by matbme** [comment]
Hi, sorry for the (very) late reply. I refactored some of the parser elements and added this specific case to it. The PR was just pushed upstream and you should be able to get it by updating your plugins.

Also, syntax highlighting might be a bit off in the near future due to an [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2600) in nvim-treesitter. I'll try to work with the devs to get it fixed.
